// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tuesaxditbquwnhqxrjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1ZXNheGRpdGJxdXduaHF4cmprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzQzNjgsImV4cCI6MjA2MzQxMDM2OH0.QiH3a_2BwbdNSwG1TSpXBJj7iYsEkQo9QCXeK8ZalfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);